@startuml
autonumber
actor User

User -> Application : delete(key)
Application -> Application : Parses input command
Application -> Table : delete(key)
Table -> BTree : Finds code in BTree
BTree -> LeafDatablock : Gets RowId
LeafDatablock --> BTree
BTree --> Table : Record RowId
Table -> Buffer : Get data block
Buffer -> Datafile : Get data block
database Disk
Datafile -> Disk : Get data block from disk
Disk --> Datafile
Datafile --> Buffer
Buffer --> Table
Table -> TableDatablock : delete Record
TableDatablock -> TableDatablock : Update header
TableDatablock --> Table
Table -> BTree : Delete key from leaf
BTree --> Table
Table --> Application
Application --> User : Result
@enduml
